### PR TITLE
Migrate Button component to TypeScript and add css modules to types 

### PR DESCRIPTION
**Pull request by ivanday**
Created new pull request on branch "typescript_button_migration" according to contribution guidelines

### CODE REVIEW

**Comment by arielge** [comment]
@ivanday
Welcome to the Label Sleuth community, and thank you for contributing!

A couple comments:
1. I ran our test workflow and it appears these changes result in the following error:
```
TS1208: 'ButtonLogout.tsx' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.
Error: Process completed with exit code 1.
```
Note that you can try building the frontend on your machine by following the instructions [here](https://github.com/label-sleuth/label-sleuth/tree/main/frontend). @martinscooper should be able to help you out if you have any questions.
2. can you please add a copy of the [Developer's Certificate of Origin 1.1](https://elinux.org/Developer_Certificate_Of_Origin) to the PR description (as outlined in the [Contribution Guidelines](https://github.com/label-sleuth/label-sleuth/blob/main/CONTRIBUTING.md#contributor-license-agreement))? [Here](https://github.com/label-sleuth/label-sleuth/pull/336) you can see an example. Thanks!

**Comment by martinscooper** [comment]
Hi @ivanday. Thank you very much for contributing with the Typescript migration effort! Overall, the changes look very good. I would like you to make the following changes before we merge it:
- Remove the `ButtonLogout` file. It seems like we forgot to remove it on an old refactor.
- Revert the changes in `tsconfig.json` that sets the `include` option to only match `ts` or `tsx` files. As we are in the middle of the migration (the `allowJs` option is true), we want the typescript compiler to also output `js` and `jsx` files, which is what setting it to only `"src"` does. Quoting the documentation: `If a glob pattern doesn’t include a file extension, then only files with supported extensions are included (e.g. .ts, .tsx, and .d.ts by default, with .js and .jsx if allowJs is set to true).`

Thanks again and welcome to the Label Sleuth community :)

**Comment by martinscooper** [comment]
Hi @ivanday, have you had the chance to look into my comments?

**Comment by ivanday** [comment]
Yes, I will finalize changes and submit new PR tonight, thanks

**Comment by martinscooper** [comment]
Hi @ivanday, are you planning to apply the suggested changes?

**Comment by martinscooper** [comment]
Closing this and finishing the work myself. @ivanday I set you as the co-author of the corresponding commit in https://github.com/label-sleuth/label-sleuth/pull/527.

**Pull request closed without merging**
